import { WEARABLE_ACCESSORY, WEARABLE_ARM, WEARABLE_CHEST, WEARABLE_HEAD, WEARABLE_LEG, WEARABLE_WEAPON } from "../models/wearable";

var database = [["search", "scissors.png", "Scissors", "Alley,Hospital,School", 1, WEARABLE_WEAPON],
["search", "fountain_pen.png", "Fountain Pen", "Uptown,Avenue,School", 1, WEARABLE_WEAPON],
["search", "kitchen_knife.png", "Kitchen Knife", "Dock,Hotel,Temple", 1, WEARABLE_WEAPON],
["dagger", "army_knife.png", "Army Knife", "Kitchen Knife,Branch", "Uncommon", "Attack Power +14,Movement Speed +0.08,Movement Speed Out of Combat +0.2,"],
["dagger", "scalpel.png", "Scalpel", "Fountain Pen,Razor", "Uncommon", "Attack Power +18,"],
["dagger", "rose_knife.png", "Rose Knife", "Army Knife,Flower", "Rare", "Attack Power +20,Cooldown Reduction +8%,Movement Speed +0.1,Movement Speed Out of Combat +0.1,"],
["dagger", "swiss_army_knife.png", "Swiss Army Knife", "Scalpel,Scissors", "Rare", "Attack Power +23,Max HP +100,"],
["dagger", "carnwennan.png", "Carnwennan", "Rose Knife,Saint's Relic", "Epic", "Attack Power +41,HP Regen +1.2,Cooldown Reduction +12%,Movement Speed +0.1,Movement Speed Out of Combat +0.1,Extra Normal Attack Damage +29,"],
["dagger", "mount_slicer.png", "Mount Slicer", "Rose Knife,Ash", "Epic", "Attack Power +35,Cooldown Reduction +15%,Movement Speed +0.1,Movement Speed Out of Combat +0.1,Extra Skill Damage +30,"],
["dagger", "vibroblade.png", "Vibroblade", "Army Knife,Motor", "Epic", "Attack Power +55,Attack Speed +40%,Movement Speed +0.1,Movement Speed Out of Combat +0.1,"],
["dagger", "damascus_steel_thorn.png", "Damascus Steel Thorn", "Swiss Army Knife,Spiked Plank", "Epic", "Attack Power +66,Max HP +250,Healing Reduction (Skills) +1,"],
["dagger", "fragarach.png", "Fragarach", "Army Knife,Force Core", "Legendary", "Attack Power +95,Movement Speed +0.22,Movement Speed Out of Combat +0.1,"],
["search", "rusty_sword.png", "Rusty Sword", "Dock,Archery Range,Chapel", 1, WEARABLE_WEAPON],
["two_handed_sword", "shamshir.png", "Shamshir", "Rusty Sword,Lighter", "Uncommon", "Attack Power +27,"],
["two_handed_sword", "katana.png", "Katana", "Rusty Sword,Iron Sheet", "Rare", "Attack Power +35,"],
["two_handed_sword", "masamune.png", "Masamune", "Katana,Oil", "Rare", "Attack Power +40,Attack Speed +15%,"],
["two_handed_sword", "muramasa.png", "Muramasa", "Katana,Gemstone", "Rare", "Attack Power +50,"],
["two_handed_sword", "bastard_sword.png", "Bastard Sword", "Rusty Sword,Steel", "Rare", "Attack Power +45,Movement Speed -0.05,"],
["two_handed_sword", "jewel_sword.png", "Jewel Sword", "Shamshir,Ruby", "Rare", "Attack Power +35,Max HP +200,"],
["two_handed_sword", "thu\u1eadn_thien.png", "Thu\u1eadn Thi\u00ean", "Bastard Sword,Turtle Shell", "Rare", "Attack Power +77,Defense +25,"],
["two_handed_sword", "arondight.png", "Arondight", "Masamune,Cross", "Epic", "Attack Power +50,Attack Speed +30%,Extra Normal Attack Damage +25,"],
["two_handed_sword", "excalibur.png", "Excalibur", "Jewel Sword,Holy Grail", "Epic", "Attack Power +60,Max HP +360,HP Regen +200%,Attack Speed +10%,"],
["two_handed_sword", "plasma_sword.png", "Plasma Sword", "Bastard Sword,Laser Pointer", "Rare", "Attack Power +75,Vision Range +3,"],
["two_handed_sword", "laevateinn.png", "Laevateinn", "True Samadhi Fire,Shamshir", "Legendary", "Attack Power +78,HP Regen +2,SP Regen +2,Attack Speed +10%,Extra Normal Attack Damage +25,"],
["two_handed_sword", "monohoshizao.png", "Monohoshizao", "Muramasa,Blueprint", "Epic", "Attack Power +80,Life Steal +25%,"],
["two_handed_sword", "hovud.png", "Hovud", "Jewel Sword,Glass Pieces", "Epic", "Attack Power +50,Max HP +300,Critical Strike Chance +28%,"],
["two_handed_sword", "dainsleif.png", "D\u00e1insleif", "VF Blood Sample,Katana", "Legendary", "Attack Power +83,Life Steal +25%,Healing Reduction (Attacks) +1,"],
["dual_swords", "twin_swords.png", "Twin Swords", "Kitchen Knife,Rusty Sword", "Uncommon", "Attack Power +18,Attack Speed +10%,"],
["dual_swords", "florentine.png", "Florentine", "Twin Swords,Blueprint", "Rare", "Attack Power +28,Attack Speed +10%,Life Steal +10%,"],
["dual_swords", "divine_dual_swords.png", "Divine Dual Swords", "Florentine,Nail", "Epic", "Attack Power +49,Attack Speed +12%,Life Steal +20%,Healing Reduction (Skills) +1,"],
["dual_swords", "starsteel_twin_swords.png", "Starsteel Twin Swords", "Twin Swords,Moonstone", "Epic", "Attack Power +60,Attack Speed +40%,Extra Normal Attack Damage +8,"],
["dual_swords", "dioscuri.png", "Dioscuri", "Twin Swords,Ion Battery", "Epic", "Attack Power +48,Attack Speed +50%,"],
["dual_swords", "lloigor_-_zahr.png", "Lloigor & Zahr", "Twin Swords,Poison", "Epic", "Attack Power +38,Attack Speed +20%,Extra Skill Damage +38,"],
["search", "hammer.png", "Hammer", "Pond,Beach,Alley", 1, WEARABLE_WEAPON],
["hammer", "warhammer.png", "Warhammer", "Hammer,Short Rod", "Uncommon", "Attack Power +40,"],
["hammer", "morning_star.png", "Morning Star", "Warhammer,Iron Ball", "Rare", "Attack Power +55,"],
["hammer", "black_stag_hammer.png", "Black Stag Hammer", "Warhammer,Leather", "Rare", "Attack Power +56,"],
["hammer", "fang_mace.png", "Fang Mace", "Morning Star,Heated Stone", "Epic", "Attack Power +55,Extra Skill Damage +33,"],
["hammer", "hammer_of_dagda.png", "Hammer of Dagda", "Black Stag Hammer,Saint's Relic", "Epic", "Attack Power +95,HP Regen +200%,Extra Normal Attack Damage +22,"],
["hammer", "hammer_of_thor.png", "Hammer of Thor", "Black Stag Hammer,Ion Battery", "Epic", "Attack Power +120,Attack Speed +40%,"],
["hammer", "evening_star.png", "Evening Star", "Moonstone,Morning Star", "Epic", "Attack Power +137,"],
["hammer", "magic_stick.png", "Magic Stick", "Warhammer,Moonlight Pendant", "Epic", "Attack Power +55,Life Steal +30%,Vision Range +0.5,Spell Amplification +27%,"],
["search", "pickaxe.png", "Pickaxe", "Pond,Beach,Cemetery,Forest", 1, WEARABLE_WEAPON],
["search", "hatchet.png", "Hatchet", "Pond,Beach,Factory", 1, WEARABLE_WEAPON],
["axe", "chain_scythe.png", "Chain Scythe", "Pickaxe,Steel Chain", "Uncommon", "Attack Power +50,Attack Range +0.2,"],
["axe", "battle_axe.png", "Battle Axe", "Hatchet,Bamboo", "Uncommon", "Attack Power +47,"],
["axe", "light_hatchet.png", "Light Hatchet", "Battle Axe,Feather", "Rare", "Attack Power +61,Movement Speed +0.05,"],
["axe", "reapers_scythe.png", "Reaper's Scythe", "Chain Scythe,Short Rod", "Rare", "Attack Power +80,Attack Range +0.5,"],
["axe", "gigantic_axe.png", "Gigantic Axe", "Battle Axe,Steel", "Rare", "Attack Power +110,Movement Speed -0.1,"],
["axe", "beam_axe.png", "Beam Axe", "Gigantic Axe,Laser Pointer", "Epic", "Attack Power +127,Vision Range +3.5,"],
["axe", "santa_muerte.png", "Santa Muerte", "Reaper's Scythe,Ruby", "Epic", "Attack Power +100,Max HP +365,Life Steal +15%,Attack Range +0.5,"],
["axe", "scythe.png", "Scythe", "Reaper's Scythe,Gold", "Epic", "Attack Power +112,Attack Range +1,Spell Amplification +20%,"],
["axe", "parashu.png", "Parashu", "Light Hatchet,Buddha Sarira", "Epic", "Attack Power +115,Cooldown Reduction +10%,Movement Speed +0.07,"],
["axe", "harpe.png", "Harpe", "Reaper's Scythe,White Crane Fan", "Epic", "Attack Power +105,Movement Speed +0.07,Attack Range +0.5,Extra Skill Damage +33,Healing Reduction (Skills) +1,"],
["search", "short_spear.png", "Short Spear", "Pond,Temple,Forest", 1, WEARABLE_WEAPON],
["spear", "bamboo_spear.png", "Bamboo Spear", "Short Spear,Bamboo", "Uncommon", "Attack Power +37,"],
["spear", "bident.png", "Bident", "Bamboo Spear,Kitchen Knife", "Rare", "Attack Power +52,"],
["spear", "pike.png", "Pike", "Short Spear,Steel", "Rare", "Attack Power +53,Movement Speed -0.1,"],
["spear", "halberd_axe.png", "Halberd Axe", "Hatchet,Pike", "Rare", "Attack Power +85,Movement Speed -0.1,"],
["spear", "sharpened_spear.png", "Sharpened Spear", "Bamboo Spear,Feather", "Rare", "Attack Power +40,Movement Speed +0.1,"],
["spear", "gentian_silver_gun.png", "Gentian Silver Gun", "Sharpened Spear,White Powder", "Epic", "Attack Power +108,Movement Speed +0.12,"],
["spear", "eighteen_foot_spear.png", "Eighteen Foot Spear", "Sharpened Spear,Ion Battery", "Epic", "Attack Power +104,Attack Speed +40%,"],
["spear", "cosmic_bident.png", "Cosmic Bident", "Bident,Moonstone", "Epic", "Attack Power +138,"],
["spear", "lance_of_poseidon.png", "Lance of Poseidon", "Bident,Pike", "Epic", "Attack Power +90,Cooldown Reduction +7%,Spell Amplification +21%,"],
["spear", "blazing_lance.png", "Blazing Lance", "True Samadhi Fire,Bamboo Spear", "Legendary", "Attack Power +115,HP Regen +2,SP Regen +2,Extra Normal Attack Damage +33,"],
["spear", "fangtian_huaji.png", "Fangtian Huaji", "Halberd Axe,Gilded Quill Fan", "Epic", "Attack Power +84,Movement Speed -0.07,Extra Skill Damage +31,Healing Reduction (Skills) +1,"],
["spear", "dragon_guandao.png", "Dragon Guandao", "Halberd Axe,Iron Sheet", "Epic", "Attack Power +118,Max HP +320,Movement Speed -0.05,"],
["spear", "spear_of_longinus.png", "Spear of Longinus", "VF Blood Sample,Pike", "Legendary", "Attack Power +130,Life Steal +20%,"],
["search", "branch.png", "Branch", "NA", 1, WEARABLE_WEAPON],
["search", "short_rod.png", "Short Rod", "Dock,Pond,Temple", 1, WEARABLE_WEAPON],
["bat", "long_rod.png", "Long Rod", "Short Rod,Bamboo", "Uncommon", "Attack Power +22,"],
["bat", "goblin_bat.png", "Goblin Bat", "Long Rod,Nail", "Rare", "Attack Power +27,Healing Reduction (Attacks) +1,"],
["bat", "umbrella.png", "Umbrella", "Long Rod,Fan", "Rare", "Attack Power +30,Extra Skill Damage +14,"],
["bat", "torch.png", "Torch", "Short Rod,Oilcloth", "Rare", "Attack Power +36,HP Regen +0.5,Attack Speed +10%,"],
["bat", "statue_of_soteria.png", "Statue of Soteria", "Torch,Doll", "Epic", "Attack Power +78,HP Regen +0.6,SP Regen +80%,Attack Speed +15%,Life Steal +12%,"],
["bat", "mallet.png", "Mallet", "Goblin Bat,Electronic Parts", "Epic", "Attack Power +85,Attack Speed +50%,Healing Reduction (Attacks) +1,"],
["bat", "spy_umbrella.png", "Spy Umbrella", "Umbrella,Ash", "Epic", "Attack Power +65,SP Regen +0.8,Extra Skill Damage +30,"],
["bat", "monkey_king_bar.png", "Monkey King Bar", "Force Core,Long Rod", "Legendary", "Attack Power +140,Attack Range +1,"],
["search", "whip.png", "Whip", "Chapel,School", 1, WEARABLE_WEAPON],
["whip", "rope_cuffs.png", "Rope Cuffs", "Whip,Stallion Medal", "Uncommon", "Attack Power +24,Extra Skill Damage +6,"],
["whip", "bullwhip.png", "Bullwhip", "Whip,Razor", "Uncommon", "Attack Power +30,"],
["whip", "wind_whip.png", "Wind Whip", "Rope Cuffs,Fan", "Rare", "Attack Power +24,Extra Skill Damage +20,"],
["whip", "thunder_whip.png", "Thunder Whip", "Bullwhip,Gold", "Rare", "Attack Power +40,Spell Amplification +24%,"],
["whip", "lightning_whip.png", "Lightning Whip", "Bullwhip,Dead Battery", "Rare", "Attack Power +42,Attack Speed +20%,"],
["whip", "gleipnir.png", "Gleipnir", "Wind Whip,Spiked Plank", "Epic", "Attack Power +58,Extra Skill Damage +40,"],
["whip", "plasma_whip.png", "Plasma Whip", "Lightning Whip,Laser Pointer", "Epic", "Attack Power +64,Attack Speed +40%,Vision Range +2.3,Extra Normal Attack Damage +15,"],
["whip", "bloody_nine_tails.png", "Bloody Nine Tails", "VF Blood Sample,Wind Whip", "Legendary", "Attack Power +70,Life Steal +25%,Extra Skill Damage +44,"],
["search", "brass_knuckles.png", "Brass Knuckles", "Cemetery,Forest", 1, WEARABLE_WEAPON],
["search", "cotton_gloves.png", "Cotton Gloves", "Hotel,Hospital", 1, WEARABLE_WEAPON],
["glove", "leather_gloves.png", "Leather Gloves", "Cotton Gloves,Leather", "Uncommon", "Attack Power +18,"],
["glove", "iron_knuckles.png", "Iron Knuckles", "Brass Knuckles,Iron Ore", "Uncommon", "Attack Power +20,"],
["glove", "gauntlet.png", "Gauntlet", "Cotton Gloves,Steel", "Rare", "Attack Power +28,Movement Speed -0.1,"],
["glove", "wing_knuckles.png", "Wing Knuckles", "Iron Knuckles,Feather", "Rare", "Attack Power +20,Movement Speed +0.1,"],
["glove", "bone_gauntlet.png", "Bone Gauntlet", "Gauntlet,Turtle Shell", "Rare", "Attack Power +35,Defense +13,Movement Speed -0.05,"],
["glove", "shatter_shell_gauntlet.png", "Shatter Shell Gauntlet", "Gauntlet,Gunpowder", "Rare", "Attack Power +32,Movement Speed -0.1,Extra Normal Attack Damage +15,"],
["glove", "glass_knuckles.png", "Glass Knuckles", "Iron Knuckles,Glass Pieces", "Rare", "Attack Power +28,Critical Strike Chance +10%,"],
["glove", "phoenix_gloves.png", "Phoenix Gloves", "Leather Gloves,Ash", "Rare", "Attack Power +27,Extra Skill Damage +30,"],
["glove", "one_inch_punch.png", "One Inch Punch", "Bone Gauntlet,Doll", "Epic", "Attack Power +50,Defense +18,SP Regen +50%,Life Steal +12%,"],
["glove", "divine_fist.png", "Divine Fist", "Shatter Shell Gauntlet,Cross", "Epic", "Attack Power +55,Movement Speed -0.1,Extra Normal Attack Damage +39,"],
["glove", "bloodwing_knuckles.png", "Bloodwing Knuckles", "Wing Knuckles,Ruby", "Epic", "Attack Power +53,Max HP +210,Movement Speed +0.1,"],
["glove", "frost_petal_hand.png", "Frost Petal Hand", "Phoenix Gloves,Ice", "Epic", "Attack Power +35,Cooldown Reduction +15%,Extra Skill Damage +38,"],
["glove", "buddhas_palm.png", "Buddha's Palm", "Phoenix Gloves,Buddha Sarira", "Epic", "Attack Power +43,Cooldown Reduction +19%,Spell Amplification +19%,"],
["glove", "brasil_gauntlet.png", "Brasil Gauntlet", "Bone Gauntlet,Oilcloth", "Epic", "Attack Power +50,Defense +10,HP Regen +1.2,SP Regen +1.2,Attack Speed +35%,Movement Speed -0.07,"],
["glove", "white_claw_punch.png", "White Claw Punch", "Glass Knuckles,White Powder", "Epic", "Attack Power +58,Critical Strike Chance +33%,"],
["glove", "imperial_silk_gloves.png", "Imperial Silk Gloves", "Mithril String,Leather Gloves", "Epic", "Attack Power +88,Movement Speed +0.12,"],
["search", "bamboo.png", "Bamboo", "Pond,Temple,Archery Range,Cemetery,Forest", 1, WEARABLE_WEAPON],
["tonfa", "wooden_tonfa.png", "Wooden Tonfa", "Bamboo,Branch", "Uncommon", "Attack Power +23,Defense +8,"],
["tonfa", "police_baton.png", "Police Baton", "Wooden Tonfa,Stallion Medal", "Rare", "Attack Power +31,Defense +10,"],
["tonfa", "ryukyu_tonfa.png", "Ryukyu Tonfa", "Wooden Tonfa,White Powder", "Rare", "Attack Power +38,Defense +18,"],
["tonfa", "tactical_tonfa.png", "Tactical Tonfa", "Police Baton,Blueprint", "Epic", "Attack Power +74,Defense +16,Life Steal +25%,"],
["tonfa", "mai_sok.png", "Mai Sok", "Ryukyu Tonfa,Short Rod", "Epic", "Attack Power +63,Defense +25,HP Regen +100%,"],
["tonfa", "plasma_tonfa.png", "Plasma Tonfa", "Ryukyu Tonfa,Laser Pointer", "Epic", "Attack Power +65,Defense +24,Vision Range +2.5,"],
["search", "iron_ball.png", "Iron Ball", "Archery Range,Forest,Factory", 1, WEARABLE_WEAPON],
["search", "baseball.png", "Baseball", "NA", 1, WEARABLE_WEAPON],
["throw", "grenade.png", "Grenade", "Iron Ball,Gunpowder", "Uncommon", "Attack Power +25,Extra Normal Attack Damage +20,"],
["throw", "molotov_cocktail.png", "Molotov Cocktail", "Glass Bottle,Oil", "Uncommon", "Attack Power +22,Attack Speed +15%,"],
["throw", "sling.png", "Sling", "Signed Ball,Rubber", "Rare", "Attack Power +42,"],
["throw", "signed_ball.png", "Signed Ball", "Baseball,Fountain Pen", "Uncommon", "Attack Power +30,"],
["throw", "flour_bomb.png", "Flour Bomb", "White Powder,Molotov Cocktail", "Rare", "Attack Power +58,Attack Speed +15%,"],
["throw", "incendiary_bomb.png", "Incendiary Bomb", "Molotov Cocktail,Ball Lightning", "Epic", "Attack Power +66,Attack Speed +60%,Cooldown Reduction +10%,"],
["throw", "ball_lightning.png", "Ball Lightning", "Iron Ball,Dead Battery", "Rare", "Attack Power +24,Attack Speed +20%,"],
["throw", "flubber.png", "Flubber", "Rubber,Boiling Water", "Rare", "Attack Power +42,"],
["throw", "grenade_of_antioch.png", "Grenade of Antioch", "High Explosive Grenade,Cross", "Epic", "Attack Power +77,Extra Normal Attack Damage +100,"],
["throw", "davids_sling.png", "David's Sling", "Sling,Saint's Relic", "Epic", "Attack Power +68,HP Regen +200%,Extra Normal Attack Damage +33,"],
["throw", "smoke_bomb.png", "Smoke Bomb", "Flour Bomb,Cola", "Epic", "Attack Power +85,Attack Speed +40%,"],
["throw", "spiky_bouncy_ball.png", "Spiky Bouncy Ball", "Flubber,Nail", "Rare", "Attack Power +45,Healing Reduction (Skills) +1,"],
["throw", "high_explosive_grenade.png", "High Explosive Grenade", "Grenade,RDX", "Epic", "Attack Power +56,Extra Normal Attack Damage +60,"],
["throw", "ruthenium_marble.png", "Ruthenium Marble", "Spiky Bouncy Ball,Gold", "Epic", "Attack Power +76,Spell Amplification +28%,Healing Reduction (Skills) +1,"],
["search", "razor.png", "Razor", "Hospital,Chapel,School", 1, WEARABLE_WEAPON],
["search", "playing_cards.png", "Playing Cards", "Hotel,Avenue", 1, WEARABLE_WEAPON],
["search", "chalk.png", "Chalk", "Factory,Chapel,School", 1, WEARABLE_WEAPON],
["shuriken", "dart.png", "Dart", "Needle,Feather", "Uncommon", "Attack Power +16,Critical Strike Damage +15%,Movement Speed +0.1,"],
["shuriken", "charm.png", "Charm", "Vintage Cards,Buddhist Scripture", "Rare", "Attack Power +40,Spell Amplification +10%,"],
["shuriken", "vintage_cards.png", "Vintage Cards", "Playing Cards,Fountain Pen", "Uncommon", "Attack Power +15,Critical Strike Chance +10%,"],
["shuriken", "throwing_stars.png", "Throwing Stars", "Razor,Piano Wire", "Uncommon", "Attack Power +27,"],
["shuriken", "onyx_dagger.png", "Onyx Dagger", "Razor,Cross", "Uncommon", "Attack Power +17,Extra Normal Attack Damage +10,"],
["shuriken", "willow_leaf_spike.png", "Willow Leaf Spike", "Onyx Dagger,Branch", "Rare", "Attack Power +17,Extra Normal Attack Damage +20,"],
["shuriken", "chakram.png", "Chakram", "Throwing Stars,Stallion Medal", "Rare", "Attack Power +30,"],
["shuriken", "apricot_flower_tag.png", "Apricot Flower Tag", "Willow Leaf Spike,Flower", "Rare", "Attack Power +17,Cooldown Reduction +10%,Extra Normal Attack Damage +30,"],
["shuriken", "cards_of_tyranny.png", "Cards of Tyranny", "Vintage Cards,Ion Battery", "Epic", "Attack Power +49,Attack Speed +40%,Critical Strike Chance +25%,Critical Strike Damage +10%,"],
["shuriken", "venom_dart.png", "Venom Dart", "Needle,Poison", "Rare", "Attack Power +55,Critical Strike Damage +20%,Extra Skill Damage +15,"],
["shuriken", "dharma_chakram.png", "Dharma Chakram", "Chakram,Buddhist Scripture", "Rare", "Attack Power +38,Spell Amplification +15%,"],
["shuriken", "plumbata.png", "Plumbata", "Dart,Steel", "Rare", "Attack Power +48,Critical Strike Damage +15%,Movement Speed +0.18,"],
["shuriken", "mystic_jade_charm.png", "Mystic Jade Charm", "Charm,Ash", "Epic", "Attack Power +60,Extra Skill Damage +15,Spell Amplification +15%,"],
["shuriken", "fuhma_shuriken.png", "Fuhma Shuriken", "Apricot Flower Tag,Alcohol", "Epic", "Attack Power +58,Cooldown Reduction +15%,Extra Normal Attack Damage +40,"],
["shuriken", "frost_venom_dart.png", "Frost Venom Dart", "Venom Dart,Ice", "Epic", "Attack Power +80,Critical Strike Damage +50%,Extra Skill Damage +20,"],
["shuriken", "azure_dagger.png", "Azure Dagger", "Onyx Dagger,Poison", "Epic", "Attack Power +20,Extra Normal Attack Damage +33,Extra Skill Damage +24,"],
["shuriken", "flechette.png", "Flechette", "Plumbata,White Powder", "Epic", "Attack Power +85,Critical Strike Damage +15%,Movement Speed +0.25,Attack Range +0.5,"],
["shuriken", "wind_and_fire_wheels.png", "Wind and Fire Wheels", "Dharma Chakram,Bamboo", "Epic", "Attack Power +53,Spell Amplification +23%,"],
["shuriken", "death_rune.png", "Death Rune", "Charm,Tree of Life", "Epic", "Attack Power +80,Spell Amplification +25%,"],
["shuriken", "sudarsana.png", "Sudarsana", "Force Core,Throwing Stars", "Legendary", "Attack Power +130,"],
["shuriken", "petal_torrent.png", "Petal Torrent", "Frost Venom Dart,Stingburst", "Legendary", "Attack Power +85,Critical Strike Damage +30%,Extra Normal Attack Damage +150,Extra Skill Damage +30,"],
["search", "bow.png", "Bow", "Archery Range,Chapel", 1, WEARABLE_WEAPON],
["bow", "wooden_bow.png", "Wooden Bow", "Branch,Piano Wire", "Uncommon", "Attack Power +26,"],
["bow", "longbow.png", "Longbow", "Bow,Rubber", "Uncommon", "Attack Power +25,"],
["bow", "composite_bow.png", "Composite Bow", "Longbow,Nail", "Rare", "Attack Power +25,Healing Reduction (Attacks) +1,"],
["bow", "strong_bow.png", "Strong Bow", "Wooden Bow,Oil", "Rare", "Attack Power +26,Attack Speed +15%,"],
["bow", "stallion_bow.png", "Stallion Bow", "Mighty Bow,Stallion Medal", "Rare", "Attack Power +20,Extra Normal Attack Damage +25,"],
["bow", "mighty_bow.png", "Mighty Bow", "Longbow,Gunpowder", "Rare", "Attack Power +25,Extra Normal Attack Damage +11,"],
["bow", "pellet_bow.png", "Pellet Bow", "Wooden Bow,Heated Stone", "Rare", "Attack Power +55,"],
["bow", "ancient_bolt.png", "Ancient Bolt", "Stallion Bow,Bamboo", "Epic", "Attack Power +60,Extra Normal Attack Damage +48,"],
["bow", "scorchbow.png", "Scorchbow", "Longbow,Lighter", "Rare", "Attack Power +22,Extra Skill Damage +18,"],
["bow", "golden-ratio_bow.png", "Golden-Ratio Bow", "Pellet Bow,Gold", "Epic", "Attack Power +68,Cooldown Reduction +15%,Spell Amplification +20%,"],
["bow", "twinbow.png", "Twinbow", "Strong Bow,Composite Bow", "Epic", "Attack Power +74,Attack Speed +55%,Vision Range +1,Healing Reduction (Attacks) +1,"],
["bow", "elemental_bow.png", "Elemental Bow", "Scorchbow,White Crane Fan", "Epic", "Attack Power +60,Movement Speed +0.13,Extra Skill Damage +45,Healing Reduction (Skills) +1,"],
["bow", "failnaught.png", "Failnaught", "VF Blood Sample,Strong Bow", "Legendary", "Attack Power +100,Attack Speed +15%,Life Steal +15%,"],
["search", "short_crossbow.png", "Short Crossbow", "Forest,Factory", 1, WEARABLE_WEAPON],
["crossbow", "long_crossbow.png", "Long Crossbow", "Short Crossbow,Piano Wire", "Uncommon", "Attack Power +30,"],
["crossbow", "crossbow.png", "Crossbow", "Short Crossbow,Bamboo", "Uncommon", "Attack Power +30,"],
["crossbow", "power_crossbow.png", "Power Crossbow", "Long Crossbow,Rubber", "Rare", "Attack Power +42,"],
["crossbow", "laser_crossbow.png", "Laser Crossbow", "Crossbow,Laser Pointer", "Rare", "Attack Power +30,Vision Range +2.5,"],
["crossbow", "heavy_crossbow.png", "Heavy Crossbow", "Long Crossbow,Steel", "Rare", "Attack Power +63,Movement Speed -0.1,"],
["crossbow", "steel_bow.png", "Steel Bow", "Crossbow,Iron Sheet", "Rare", "Attack Power +60,"],
["crossbow", "the_legend_of_the_general.png", "The Legend of The General", "Steel Bow,Oilcloth", "Epic", "Attack Power +75,HP Regen +2,Attack Speed +50%,"],
["crossbow", "ballista.png", "Ballista", "Heavy Crossbow,Short Spear", "Epic", "Attack Power +115,Attack Speed -8%,Spell Amplification +8%,"],
["crossbow", "sniper_crossbow.png", "Sniper Crossbow", "Laser Crossbow,Sniper Scope", "Epic", "Attack Power +85,Vision Range +3,Attack Range +1,"],
["crossbow", "the_golden_ghost.png", "The Golden Ghost", "Power Crossbow,RDX", "Epic", "Attack Power +66,Extra Normal Attack Damage +44,"],
["crossbow", "sharanga.png", "Sharanga", "Force Core,Crossbow", "Legendary", "Attack Power +140,Vision Range +1.5,"],
["search", "walther_ppk.png", "Walther PPK", "Beach,Hotel,Factory", 1, WEARABLE_WEAPON],
["pistol", "magnum-python.png", "Magnum-Python", "Walther PPK,Oil", "Uncommon", "Attack Power +15,Attack Speed +10%,Movement Speed +0.1,"],
["pistol", "beretta_m92f.png", "Beretta M92F", "Walther PPK,Leather", "Uncommon", "Attack Power +23,Movement Speed +0.1,"],
["pistol", "fn57.png", "FN57", "Beretta M92F,Laser Pointer", "Rare", "Attack Power +29,Movement Speed +0.1,Vision Range +2.5,"],
["pistol", "double_revolver_sp.png", "Double Revolver SP", "Magnum-Python,Beretta M92F", "Rare", "Attack Power +40,Attack Speed +10%,Movement Speed +0.1,"],
["pistol", "magnum-anaconda.png", "Magnum-Anaconda", "Magnum-Python,Blueprint", "Rare", "Attack Power +43,Attack Speed +10%,Life Steal +10%,Movement Speed +0.1,"],
["pistol", "devils_marksman.png", "Devil's Marksman", "Double Revolver SP,Ash", "Epic", "Attack Power +38,Attack Speed +15%,Movement Speed +0.1,Extra Skill Damage +42,"],
["pistol", "elegance.png", "Elegance", "FN57,Feather Duster", "Epic", "Attack Power +90,Movement Speed +0.2,Vision Range +5,"],
["pistol", "electron_blaster.png", "Electron Blaster", "Beretta M92F,Ion Battery", "Epic", "Attack Power +61,Attack Speed +55%,Movement Speed +0.12,Extra Normal Attack Damage +31,"],
["pistol", "magnum-boa.png", "Magnum-Boa", "Magnum-Anaconda,Steel", "Epic", "Attack Power +90,Attack Speed +25%,Life Steal +22%,Movement Speed +0.15,Vision Range +2.5,"],
["pistol", "kelte.png", "Kelte", "Force Core,Beretta M92F", "Legendary", "Attack Power +115,Movement Speed +0.2,Vision Range +2,"],
["search", "fedorova.png", "Fedorova", "Hotel,Factory", 1, WEARABLE_WEAPON],
["assault_rifle", "stg-44.png", "STG-44", "Fedorova,Gunpowder", "Uncommon", "Attack Power +18,Vision Range +1.5,Extra Normal Attack Damage +2,"],
["assault_rifle", "ak-47.png", "AK-47", "STG-44,Piano Wire", "Rare", "Attack Power +29,Vision Range +1.5,Extra Normal Attack Damage +2,"],
["assault_rifle", "m16a1.png", "M16A1", "STG-44,Leather", "Rare", "Attack Power +25,Vision Range +1.5,Extra Normal Attack Damage +4,"],
["assault_rifle", "machine_gun.png", "Machine Gun", "STG-44,Motor", "Epic", "Attack Power +20,Attack Speed +10%,Vision Range +1.5,Extra Normal Attack Damage +11,"],
["assault_rifle", "gatling_gun.png", "Gatling Gun", "AK-47,Steel", "Epic", "Attack Power +75,Vision Range +1.5,Attack Range +1,"],
["assault_rifle", ".png", "NA", "Machine Gun,Heated Oil", "Legendary", "Attack Power +55,Attack Speed +25%,Vision Range +2.5,Extra Normal Attack Damage +16,"],
["assault_rifle", "ak-12.png", "AK-12", "AK-47,Glass Panel", "Epic", "Attack Power +89,Critical Strike Chance +20%,Vision Range +1.5,"],
["assault_rifle", "xcr.png", "XCR", "M16A1,Magazine", "Epic", "Attack Power +66,Max HP +330,Vision Range +1.5,Extra Normal Attack Damage +10,"],
["search", "long_rifle.png", "Long Rifle", "Dock,Forest", 1, WEARABLE_WEAPON],
["sniper_rifle", "springfield.png", "Springfield", "Long Rifle,Laser Pointer", "Uncommon", "Attack Power +50,Movement Speed -0.07,Vision Range +1.5,"],
["sniper_rifle", "harpoon_gun.png", "Harpoon Gun", "Springfield,Short Spear", "Rare", "Attack Power +64,Movement Speed -0.07,Vision Range +2,"],
["sniper_rifle", "golden_rifle.png", "Golden Rifle", "Springfield,Gold", "Rare", "Attack Power +56,Movement Speed -0.07,Vision Range +2.5,Spell Amplification +18%,"],
["sniper_rifle", "railgun.png", "Railgun", "Springfield,Electronic Parts", "Rare", "Attack Power +78,Attack Speed +20%,Movement Speed -0.03,Vision Range +2,"],
["sniper_rifle", "tac-50.png", "Tac-50", "Harpoon Gun,Blueprint", "Epic", "Attack Power +128,Life Steal +20%,Vision Range +2.5,"],
["sniper_rifle", "intervention.png", "Intervention", "Harpoon Gun,Telephoto Camera", "Epic", "Attack Power +120,Vision Range +5,Attack Range +1.5,"],
["sniper_rifle", "ntw-20.png", "NTW-20", "Golden Rifle,Iron Sheet", "Epic", "Attack Power +92,Movement Speed -0.07,Vision Range +2.5,Spell Amplification +24%,"],
["sniper_rifle", "polaris.png", "Polaris", "Railgun,White Powder", "Epic", "Attack Power +110,Attack Speed +35%,Vision Range +2,"],
["sniper_rifle", "the_deadly_ray.png", "The Deadly Ray", "Moonstone,Golden Rifle", "Legendary", "Attack Power +100,Movement Speed -0.03,Vision Range +2.5,Spell Amplification +33%,"],
["search", "steel_chain.png", "Steel Chain", "Beach,Alley,Cemetery", 1, WEARABLE_WEAPON],
["nunchaku", "nunchaku.png", "Nunchaku", "Steel Chain,Scrap Metal", "Uncommon", "Attack Power +29,"],
["nunchaku", "sharper.png", "Sharper", "Nunchaku,Nail", "Rare", "Attack Power +29,Healing Reduction (Skills) +1,"],
["nunchaku", "bleeder.png", "Bleeder", "Nunchaku,Razor", "Rare", "Attack Power +38,"],
["nunchaku", "the_smiting_dragon.png", "The Smiting Dragon", "Sharper,Ash", "Epic", "Attack Power +50,Extra Skill Damage +20,Healing Reduction (Skills) +1,"],
["nunchaku", "vibro_nunchaku.png", "Vibro Nunchaku", "Bleeder,Motor", "Epic", "Attack Power +65,Attack Speed +50%,"],
["search", "needle.png", "Needle", "Alley,Hotel,Hospital", 1, WEARABLE_WEAPON],
["rapier", "fencing_rapier.png", "Fencing Rapier", "Needle,Iron Ore", "Uncommon", "Attack Power +16,Critical Strike Damage +15%,"],
["rapier", "apricot_sword.png", "Apricot Sword", "Fencing Rapier,Flower of Fate", "Rare", "Attack Power +25,Critical Strike Chance +10%,Critical Strike Damage +15%,Cooldown Reduction +6%,"],
["rapier", "sword_of_justice.png", "Sword of Justice", "Fencing Rapier,Covert Agent Uniform", "Epic", "Attack Power +30,HP Regen +1.5,SP Regen +150%,Critical Strike Damage +25%,Cooldown Reduction +12%,Vision Range +1,"],
["rapier", "durendal_mk2.png", "Durendal Mk2", "Apricot Sword,Laser Pointer", "Epic", "Attack Power +53,Critical Strike Chance +12%,Critical Strike Damage +25%,Cooldown Reduction +6%,Life Steal +8%,Vision Range +1.5,"],
["rapier", "mistilteinn.png", "Mistilteinn", "Sword of Justice,Branch", "Legendary", "Attack Power +35,HP Regen +1.5,SP Regen +150%,Critical Strike Damage +25%,Cooldown Reduction +15%,Vision Range +1,Spell Amplification +15%,"],
["rapier", "volticletto.png", "Volticletto", "Apricot Sword,Electronic Parts", "Epic", "Attack Power +47,Attack Speed +45%,Critical Strike Chance +10%,Critical Strike Damage +15%,Cooldown Reduction +6%,"],
["rapier", "meteor_claymore.png", "Meteor Claymore", "Apricot Sword,Meteorite", "Epic", "Attack Power +67,Critical Strike Chance +20%,Critical Strike Damage +15%,Cooldown Reduction +12%,"],
["rapier", "joyeuse.png", "Joyeuse", "Fencing Rapier,Mithril", "Epic", "Attack Power +69,Attack Speed +12%,Critical Strike Damage +20%,Movement Speed +0.2,"],
["guitar", "starter_guitar.png", "Starter Guitar", "Bamboo,Piano Wire", "Common", "Attack Power +5,"],
["guitar", "golden_bridge.png", "Golden Bridge", "Starter Guitar,Gold", "Uncommon", "Attack Power +8,Spell Amplification +14%,"],
["guitar", "single_coil_pickup.png", "Single Coil Pickup", "Starter Guitar,Dead Battery", "Uncommon", "Attack Power +8,Attack Speed +15%,Extra Normal Attack Damage +2,"],
["guitar", "ruby_special.png", "Ruby Special", "Single Coil Pickup,Ruby", "Rare", "Attack Power +20,Max HP +300,Attack Speed +20%,Extra Normal Attack Damage +2,"],
["guitar", "humbucker_pickup.png", "Humbucker Pickup", "Golden Bridge,Sniper Scope", "Rare", "Attack Power +25,Vision Range +3,Spell Amplification +15%,"],
["guitar", "king-v.png", "King-V", "Golden Bridge,Scissors", "Rare", "Attack Power +13,Spell Amplification +16%,"],
["guitar", "nocaster.png", "Nocaster", "Single Coil Pickup,Blueprint", "Rare", "Attack Power +15,Attack Speed +20%,Life Steal +10%,Extra Normal Attack Damage +10,"],
["guitar", "superstrat.png", "Superstrat", "Single Coil Pickup,Bamboo", "Rare", "Attack Power +19,Attack Speed +15%,Extra Normal Attack Damage +2,"],
["guitar", "wild_horse.png", "Wild Horse", "Single Coil Pickup,Oil", "Rare", "Attack Power +9,Attack Speed +25%,Extra Normal Attack Damage +6,"],
["guitar", "bohemian.png", "Bohemian", "Ruby Special,Playing Cards", "Epic", "Attack Power +53,Max HP +350,Attack Speed +20%,Critical Strike Chance +20%,Extra Normal Attack Damage +2,"],
["guitar", "stairway_to_heaven.png", "Stairway to Heaven", "Humbucker Pickup,Holy Grail", "Epic", "Attack Power +66,HP Regen +200%,Cooldown Reduction +5%,Vision Range +3,Spell Amplification +18%,"],
["guitar", "purple_haze.png", "Purple Haze", "King-V,Ash", "Epic", "Attack Power +85,Spell Amplification +21%,"],
["guitar", "satisfaction.png", "Satisfaction", "Nocaster,Stone", "Epic", "Attack Power +30,Attack Speed +30%,Life Steal +15%,Extra Normal Attack Damage +15,"],
["guitar", "wonderful_tonight.png", "Wonderful Tonight", "Superstrat,Meteorite", "Epic", "Attack Power +92,Attack Speed +25%,Extra Normal Attack Damage +2,"],
["guitar", "the_wall.png", "The Wall", "Superstrat,White Powder", "Epic", "Attack Power +75,Attack Speed +20%,Extra Normal Attack Damage +2,"],
["guitar", "teen_spirit.png", "Teen Spirit", "Wild Horse,Buddha Sarira", "Epic", "Attack Power +18,Attack Speed +35%,Attack Range +1,Extra Normal Attack Damage +22,"],
["search", "hairband.png", "Hairband", "Avenue,Temple,Cemetery", 1, WEARABLE_HEAD],
["search", "hat.png", "Hat", "Pond,Archery Range,School", 1, WEARABLE_HEAD],
["search", "bike_helmet.png", "Bike Helmet", "Beach,Chapel,School", 1, WEARABLE_HEAD],
["head", "mask.png", "Mask", "Hairband,Feather", "Uncommon", "Defense +10,Max SP +130,Movement Speed +0.08,"],
["head", "circlet.png", "Circlet", "Hairband,Branch", "Uncommon", "Defense +14,Max SP +270,"],
["head", "beret.png", "Beret", "Hat,Scissors", "Uncommon", "Defense +10,Max HP +60,Cooldown Reduction +7%,"],
["head", "chain_coif.png", "Chain Coif", "Hat,Steel Chain", "Uncommon", "Defense +14,Cooldown Reduction +6%,"],
["head", "safety_helmet.png", "Safety Helmet", "Bike Helmet,Stone", "Uncommon", "Max HP +200,"],
["head", "ballistic_helmet.png", "Ballistic Helmet", "Beret,Bike Helmet", "Rare", "Defense +15,Max HP +90,Cooldown Reduction +8%,"],
["head", "fire_helmet.png", "Fire Helmet", "Safety Helmet,Water", "Rare", "Max HP +250,"],
["head", "tiara.png", "Tiara", "Circlet,Stallion Medal", "Rare", "Defense +16,Max SP +400,"],
["head", "crown.png", "Crown", "Beret,Gold", "Rare", "Defense +16,Max HP +160,Spell Amplification +8%,"],
["head", "close_helm.png", "Close Helm", "Chain Coif,Mask", "Rare", "Defense +20,Max SP +130,Cooldown Reduction +7%,Movement Speed +0.08,"],
["head", "mithril_helm.png", "Mithril Helm", "Mithril,Chain Coif", "Epic", "Defense +38,Attack Speed +12%,Cooldown Reduction +15%,Movement Speed +0.2,"],
["head", "crystal_tiara.png", "Crystal Tiara", "Tiara,Glass Pieces", "Epic", "Defense +21,Max SP +600,Critical Strike Chance +22%,"],
["head", "motorcycle_helmet.png", "Motorcycle Helmet", "Fire Helmet,Binoculars", "Rare", "Attack Power +10,Max HP +300,Vision Range +1,"],
["head", "tactical_ops_helmet.png", "Tactical OPS Helmet", "Ballistic Helmet,Electronic Parts", "Epic", "Defense +15,Max HP +120,Attack Speed +25%,Cooldown Reduction +12%,"],
["head", "helm_of_banneret.png", "Helm of Banneret", "Close Helm,Rubber", "Epic", "Defense +28,Max SP +200,Cooldown Reduction +10%,Movement Speed +0.1,Spell Reduction +11%,"],
["head", "laurel_wreath.png", "Laurel Wreath", "True Samadhi Fire,Circlet", "Legendary", "Defense +20,Max SP +580,HP Regen +2,SP Regen +2,Extra Normal Attack Damage +21,"],
["head", "imperial_crown.png", "Imperial Crown", "Crown,Ruby", "Epic", "Defense +20,Max HP +350,Spell Amplification +10%,"],
["head", "imperial_burgonet.png", "Imperial Burgonet", "Close Helm,Gold", "Epic", "Defense +10,Max SP +300,Cooldown Reduction +8%,Movement Speed +0.08,Spell Amplification +18%,"],
["head", "chinese_opera_mask.png", "Chinese Opera Mask", "Mask,VF Blood Sample", "Epic", "Defense +10,Max SP +300,Life Steal +22%,Movement Speed +0.2,"],
["head", "elysian_halo.png", "Elysian Halo", "Circlet,Force Core", "Legendary", "Attack Power +35,Defense +30,Max SP +300,Critical Strike Reduction +10%,"],
["search", "windbreaker.png", "Windbreaker", "Uptown,Hotel,School", 1, WEARABLE_CHEST],
["search", "monks_robe.png", "Monk's Robe", "Temple,Archery Range", 1, WEARABLE_CHEST],
["search", "wetsuit.png", "Wetsuit", "Dock,Beach,Alley", 1, WEARABLE_CHEST],
["search", "fabric_armor.png", "Fabric Armor", "Temple,Archery Range,Cemetery", 1, WEARABLE_CHEST],
["chest", "leather_armor.png", "Leather Armor", "Fabric Armor,Leather", "Uncommon", "Defense +15,"],
["chest", "leather_jacket.png", "Leather Jacket", "Windbreaker,Leather", "Uncommon", "Defense +8,Max HP +70,Normal Attack Damage Reduction +6,"],
["chest", "turtle_dobok.png", "Turtle Dobok", "Monk's Robe,Turtle Shell", "Uncommon", "Defense +10,Cooldown Reduction +10%,"],
["chest", "military_suit.png", "Military Suit", "Windbreaker,Branch", "Uncommon", "Max HP +50,Normal Attack Damage Reduction +10,"],
["chest", "patched_robe.png", "Patched Robe", "Monk's Robe,Bandage", "Uncommon", "Defense +5,HP Regen +1,Cooldown Reduction +7%,"],
["chest", "dress.png", "Dress", "Cloth,Scissors", "Uncommon", "Attack Power +8,Defense +8,SP Regen +100%,"],
["chest", "bikini.png", "Bikini", "Wetsuit,Scissors", "Uncommon", "Defense +4,Spell Reduction +11%,"],
["chest", "diving_suit.png", "Diving Suit", "Wetsuit,Rubber", "Uncommon", "Defense +9,Spell Reduction +10%,"],
["chest", "rider_jacket.png", "Rider Jacket", "Leather Jacket,Steel Chain", "Rare", "Defense +11,Max HP +70,Normal Attack Damage Reduction +9,"],
["chest", "chain_armor.png", "Chain Armor", "Leather Armor,Steel Chain", "Rare", "Defense +30,"],
["chest", "suit.png", "Suit", "Military Suit,Ribbon", "Rare", "Life Steal +5%,Normal Attack Damage Reduction +12,"],
["chest", "qipao.png", "Qipao", "Dress,Razor", "Rare", "Attack Power +10,Defense +10,SP Regen +120%,"],
["chest", "sheet_metal_armor.png", "Sheet Metal Armor", "Fabric Armor,Steel", "Rare", "Defense +38,Max HP +100,Movement Speed -0.1,"],
["chest", "hanbok.png", "Hanbok", "Patched Robe,Flower", "Rare", "Defense +12,HP Regen +1,Cooldown Reduction +10%,"],
["chest", "bulletproof_vest.png", "Bulletproof Vest", "Military Suit,Iron Sheet", "Rare", "Defense +10,Max HP +130,Normal Attack Damage Reduction +10,"],
["chest", "sunset_armor.png", "Sunset Armor", "Leather Armor,Ruby", "Rare", "Defense +20,Max HP +360,"],
["chest", "covert_agent_uniform.png", "Covert Agent Uniform", "Hanbok,Stallion Medal", "Rare", "Defense +23,HP Regen +2.5,Cooldown Reduction +15%,Vision Range +1,"],
["chest", "optical_camouflage_suit.png", "Optical Camouflage Suit", "Diving Suit,Glass Panel", "Epic", "Attack Power +10,Defense +18,Critical Strike Chance +22%,Spell Reduction +10%,"],
["chest", "rockers_jacket.png", "Rocker's Jacket", "Rider Jacket,Clang Clatter", "Epic", "Attack Power +30,Defense +18,Normal Attack Damage Reduction +15,Healing Reduction (Skills) +1,"],
["chest", "mithril_armor.png", "Mithril Armor", "Mithril,Leather Armor", "Epic", "Defense +55,Attack Speed +12%,Movement Speed +0.2,"],
["chest", "crusader_armor.png", "Crusader Armor", "Sheet Metal Armor,Saint's Relic", "Epic", "Defense +38,HP Regen +150%,Extra Normal Attack Damage +15,"],
["chest", "amazoness_armor.png", "Amazoness Armor", "Sheet Metal Armor,Bikini", "Epic", "Defense +28,Max HP +140,Spell Reduction +20%,"],
["chest", "dragon_dobok.png", "Dragon Dobok", "Qipao,Turtle Dobok", "Epic", "Attack Power +11,Defense +10,SP Regen +120%,Cooldown Reduction +10%,Attack Range +1,"],
["chest", "commanders_armor.png", "Commander's Armor", "Chain Armor,Gold", "Epic", "Defense +24,Spell Amplification +18%,"],
["chest", "butlers_suit.png", "Butler's Suit", "Suit,Feather Duster", "Epic", "Attack Power +30,Life Steal +20%,Movement Speed +0.12,Normal Attack Damage Reduction +10,"],
["chest", "battle_suit.png", "Battle Suit", "Bulletproof Vest,Diving Suit", "Epic", "Defense +25,Max HP +170,Normal Attack Damage Reduction +15,Spell Reduction +12%,"],
["chest", "blazing_dress.png", "Blazing Dress", "True Samadhi Fire,Dress", "Legendary", "Attack Power +20,Defense +30,HP Regen +2,SP Regen +75%,SP Regen +2,Extra Normal Attack Damage +20,"],
["chest", "eod_suit.png", "EOD Suit", "Bulletproof Vest,Patched Robe", "Epic", "Defense +25,Max HP +250,HP Regen +1,Cooldown Reduction +10%,Normal Attack Damage Reduction +10,"],
["chest", "kabana.png", "Kabana", "Meteorite,Commander's Armor", "Legendary", "Defense +40,Spell Amplification +20%,"],
["chest", "queen_of_hearts.png", "Queen of Hearts", "VF Blood Sample,Hanbok", "Legendary", "Defense +37,HP Regen +3,Cooldown Reduction +25%,"],
["search", "watch.png", "Watch", "Uptown,Hotel,Avenue", 1, WEARABLE_ARM],
["search", "bandage.png", "Bandage", "Dock,Hospital,Factory,School", 1, WEARABLE_ARM],
["search", "bracelet.png", "Bracelet", "Pond,Uptown,Alley", 1, WEARABLE_ARM],
["arm", "leather_shield.png", "Leather Shield", "Turtle Shell,Leather", "Uncommon", "Attack Power +8,Defense +12,"],
["arm", "squad_leader_armband.png", "Squad Leader Armband", "Bandage,Needle", "Uncommon", "HP Regen +1.5,Critical Strike Damage +15%,"],
["arm", "bracer.png", "Bracer", "Bandage,Leather", "Uncommon", "Defense +13,HP Regen +1,"],
["arm", "broken_watch.png", "Broken Watch", "Watch,Glue", "Uncommon", "Cooldown Reduction +5%,"],
["arm", "sheath.png", "Sheath", "Leather,Iron Sheet", "Rare", "Attack Power +18,Normal Attack Damage Reduction +2,"],
["arm", "golden_bracelet.png", "Golden Bracelet", "Bracelet,Gold", "Rare", "Max SP +220,Spell Amplification +12%,"],
["arm", "bazuband.png", "Bazuband", "Bracer,Iron Sheet", "Rare", "Defense +25,Critical Strike Reduction +6%,Normal Attack Damage Reduction +8,"],
["arm", "crimson_bracelet.png", "Crimson Bracelet", "Bracelet,Spiked Plank", "Rare", "Max HP +200,Max SP +250,"],
["arm", "steel_shield.png", "Steel Shield", "Leather Shield,Steel", "Rare", "Attack Power +23,Defense +20,Movement Speed -0.05,"],
["arm", "sword_stopper.png", "Sword Stopper", "Bazuband,Nail", "Epic", "Defense +33,Critical Strike Reduction +8%,Normal Attack Damage Reduction +8,Healing Reduction (Attacks) +1,"],
["arm", "draupnir.png", "Draupnir", "Golden Bracelet,Bracer", "Epic", "Defense +10,Max SP +240,HP Regen +1,Spell Amplification +17%,"],
["arm", "mithril_shield.png", "Mithril Shield", "Mithril,Leather Shield", "Epic", "Attack Power +30,Defense +30,Attack Speed +12%,Movement Speed +0.1,"],
["arm", "vital_sign_sensor.png", "Vital Sign Sensor", "Watch,Cell Phone", "Epic", "Defense +15,Attack Speed +30%,"],
["arm", "creed_of_the_knight.png", "Creed of the Knight", "Steel Shield,Squad Leader Armband", "Epic", "Attack Power +30,Defense +20,HP Regen +1.5,Critical Strike Damage +25%,Movement Speed -0.03,"],
["arm", "sheath_of_shah_jahan.png", "Sheath of Shah Jahan", "Sheath,Ruby", "Epic", "Attack Power +30,Max HP +260,Normal Attack Damage Reduction +2,"],
["arm", "cube_watch.png", "Cube Watch", "Broken Watch,Moonstone", "Epic", "Defense +20,Attack Speed +50%,Cooldown Reduction +8%,"],
["arm", "burnished_aegis.png", "Burnished Aegis", "Crimson Bracelet,Leather Shield", "Epic", "Attack Power +8,Defense +12,Max HP +320,Max SP +250,"],
["arm", "tindalos_band.png", "Tindalos Band", "Golden Bracelet,Broken Watch", "Epic", "Cooldown Reduction +12%,Spell Amplification +12%,"],
["arm", "bracelet_of_skadi.png", "Bracelet of Skadi", "Glacial Ice,Crimson Bracelet", "Legendary", "Max HP +200,Max SP +250,HP Regen +1.5,SP Regen +1.5,Extra Skill Damage +27,"],
["arm", "radar.png", "Radar", "Vital Sign Sensor,Glass Panel", "Legendary", "Defense +15,Attack Speed +40%,Critical Strike Chance +24%,"],
["arm", "auto-arms.png", "Auto-arms", "Bracer,Force Core", "Legendary", "Attack Power +45,Defense +35,HP Regen +1,"],
["search", "slippers.png", "Slippers", "Avenue,Hospital,School", 1, WEARABLE_LEG],
["search", "running_shoes.png", "Running Shoes", "Uptown,Alley,Archery Range", 1, WEARABLE_LEG],
["search", "tights.png", "Tights", "Avenue,Hospital,Forest", 1, WEARABLE_LEG],
["leg", "knee_pads.png", "Knee Pads", "Tights,Glue", "Uncommon", "Defense +8,Movement Speed +0.16,"],
["leg", "chain_leggings.png", "Chain Leggings", "Tights,Steel Chain", "Uncommon", "Defense +10,Movement Speed +0.14,"],
["leg", "high_heels.png", "High Heels", "Slippers,Scrap Metal", "Uncommon", "SP Regen +0.8,Movement Speed +0.17,"],
["leg", "heelys.png", "Heelys", "Running Shoes,Iron Ball", "Uncommon", "Movement Speed +0.09,"],
["leg", "repaired_slippers.png", "Repaired Slippers", "Slippers,Cloth", "Uncommon", "SP Regen +30%,SP Regen +0.5,Movement Speed +0.16,"],
["leg", "boots.png", "Boots", "Running Shoes,Oilcloth", "Rare", "HP Regen +0.6,Attack Speed +2%,Movement Speed +0.22,"],
["leg", "steel_knee_pads.png", "Steel Knee Pads", "Knee Pads,Steel", "Rare", "Defense +20,Movement Speed +0.24,"],
["leg", "feather_boots.png", "Feather Boots", "Combat Boots,Feather", "Epic", "HP Regen +1,Attack Speed +35%,Movement Speed +0.4,"],
["leg", "maverick_runner.png", "Maverick Runner", "Heelys,Electronic Parts", "Rare", "Attack Speed +5%,Movement Speed +0.25,"],
["leg", "combat_boots.png", "Combat Boots", "Boots,Leather", "Rare", "HP Regen +0.6,Attack Speed +7%,Movement Speed +0.27,"],
["leg", "killer_heels.png", "Killer Heels", "High Heels,Glass Pieces", "Rare", "Attack Power +5,SP Regen +0.8,Critical Strike Chance +10%,Movement Speed +0.16,"],
["leg", "straitjacket_sneakers.png", "Straitjacket Sneakers", "Repaired Slippers,Ash", "Rare", "SP Regen +50%,SP Regen +0.5,Movement Speed +0.33,Extra Skill Damage +12,"],
["leg", "mithril_boots.png", "Mithril Boots", "Mithril,Chain Leggings", "Epic", "Defense +20,Attack Speed +12%,Movement Speed +0.5,"],
["leg", "bucephalus.png", "Bucephalus", "Killer Heels,Chain Leggings", "Epic", "Attack Power +10,Defense +10,SP Regen +1,Critical Strike Chance +15%,Movement Speed +0.33,"],
["leg", "eod_boots.png", "EOD Boots", "Boots,Steel Knee Pads", "Legendary", "Defense +26,HP Regen +1,SP Regen +0.5,Movement Speed +0.33,"],
["leg", "white_rhinos.png", "White Rhinos", "Combat Boots,Nail", "Epic", "HP Regen +0.7,Attack Speed +15%,Movement Speed +0.35,Healing Reduction (Attacks) +1,"],
["leg", "glacial_shoes.png", "Glacial Shoes", "Repaired Slippers,Glacial Ice", "Legendary", "HP Regen +1.5,SP Regen +60%,SP Regen +1.5,Movement Speed +0.3,Extra Skill Damage +24,"],
["leg", "tachyon_brace.png", "Tachyon Brace", "Knee Pads,Motor", "Epic", "Defense +15,Cooldown Reduction +10%,Movement Speed +0.38,"],
["leg", "boots_of_hermes.png", "Boots of Hermes", "Force Core,Heelys", "Legendary", "Defense +35,Movement Speed +0.4,"],
["leg", "red_shoes.png", "Red Shoes", "Killer Heels,VF Blood Sample", "Legendary", "Attack Power +5,SP Regen +1,Critical Strike Chance +10%,Life Steal +15%,Movement Speed +0.4,"],
["search", "feather.png", "Feather", "Hospital,Cemetery,Forest", 1, WEARABLE_ACCESSORY],
["search", "flower.png", "Flower", "Pond,Uptown,Cemetery,Forest", 1, WEARABLE_ACCESSORY],
["search", "ribbon.png", "Ribbon", "Pond,Uptown,School", 1, WEARABLE_ACCESSORY],
["search", "fan.png", "Fan", "Avenue,Forest,Chapel", 1, WEARABLE_ACCESSORY],
["search", "buddhist_scripture.png", "Buddhist Scripture", "Temple", 1, WEARABLE_ACCESSORY],
["search", "box.png", "Box", "Dock,Pond,Chapel", 1, WEARABLE_ACCESSORY],
["search", "holy_grail.png", "Holy Grail", "Chapel", 1, WEARABLE_ACCESSORY],
["search", "cross.png", "Cross", "Alley,Chapel", 1, WEARABLE_ACCESSORY],
["search", "binoculars.png", "Binoculars", "Beach,Alley,Hotel,Factory", 1, WEARABLE_ACCESSORY],
["accessory", "saints_relic.png", "Saint's Relic", "Cross,Holy Grail", "Uncommon", "HP Regen +150%,Extra Normal Attack Damage +8,"],
["accessory", "flower_of_fate.png", "Flower of Fate", "Flower,Playing Cards", "Uncommon", "Critical Strike Chance +15%,Cooldown Reduction +8%,"],
["accessory", "glass_pieces.png", "Glass Pieces", "Glass Bottle,Stone", "Uncommon", "Critical Strike Chance +13%,"],
["accessory", "doll.png", "Doll", "Ribbon,Cloth", "Uncommon", "SP Regen +80%,Life Steal +12%,"],
["accessory", "sniper_scope.png", "Sniper Scope", "Laser Pointer,Binoculars", "Uncommon", "Attack Power +10,Vision Range +4.5,"],
["accessory", "buddha_sarira.png", "Buddha Sarira", "Buddhist Scripture,Monk's Robe", "Uncommon", "Cooldown Reduction +8%,Spell Amplification +8%,"],
["accessory", "quiver.png", "Quiver", "Leather,Bamboo", "Uncommon", "Attack Speed +25%,"],
["accessory", "feather_duster.png", "Feather Duster", "Short Rod,Feather", "Uncommon", "Attack Power +9,Movement Speed +0.1,"],
["accessory", "gilded_quill_fan.png", "Gilded Quill Fan", "Fan,Nail", "Uncommon", "Extra Skill Damage +12,Healing Reduction (Skills) +1,"],
["accessory", "shamans_bronze.png", "Shaman's Bronze", "Rusty Sword,Stallion Medal", "Uncommon", "Attack Power +5,Spell Amplification +8%,"],
["accessory", "decorative_flintlock.png", "Decorative Flintlock", "Walther PPK,Ribbon", "Uncommon", "Attack Power +10,Life Steal +6%,"],
["accessory", "powder_of_life.png", "Powder of Life", "Tree of Life,Stone", "Rare", "HP Regen +1.5,SP Regen +1.5,"],
["accessory", "uchiwa.png", "Uchiwa", "Doll,Fan", "Rare", "SP Regen +80%,Life Steal +14%,Extra Skill Damage +23,"],
["accessory", "magazine.png", "Magazine", "Box,Iron Sheet", "Rare", "Max HP +330,Normal Attack Damage Reduction +6,"],
["accessory", "white_crane_fan.png", "White Crane Fan", "Gilded Quill Fan,Feather", "Rare", "Movement Speed +0.12,Extra Skill Damage +18,Healing Reduction (Skills) +1,"],
["accessory", "moonlight_pendant.png", "Moonlight Pendant", "Ribbon,Moonstone", "Rare", "Attack Power +24,Life Steal +16%,Vision Range +1,"],
["accessory", "laced_quiver.png", "Laced Quiver", "Quiver,Feather Duster", "Rare", "Attack Power +13,Attack Speed +30%,Movement Speed +0.1,"],
["accessory", "revenge_of_goujian.png", "Revenge of Goujian", "Shaman's Bronze,Blueprint", "Rare", "Attack Power +15,Spell Amplification +20%,"],
["accessory", "buccaneer_doubloon.png", "Buccaneer Doubloon", "Decorative Flintlock,Kitchen Knife", "Rare", "Attack Power +15,Critical Strike Chance +12%,Life Steal +6%,"],
["accessory", "schrodingers_box.png", "Schr\u00f6dinger's Box", "Box,Poison", "Rare", "Max HP +360,Extra Skill Damage +7,"],
["accessory", "veritas_lux_mea.png", "Veritas Lux Mea", "Buddha Sarira,Saint's Relic", "Rare", "HP Regen +150%,Cooldown Reduction +10%,Extra Normal Attack Damage +12,Spell Amplification +10%,"],
["accessory", "glacial_ice.png", "Glacial Ice", "Powder of Life,Ice", "Epic", "HP Regen +1.5,SP Regen +1.5,Extra Skill Damage +18,"],
["accessory", "true_samadhi_fire.png", "True Samadhi Fire", "Powder of Life,Lighter", "Epic", "HP Regen +1.5,SP Regen +1.5,Extra Normal Attack Damage +15,"],
["accessory", "lunar_embrace.png", "Lunar Embrace", "Purified Water,Moonstone", "Epic", "Defense +11,SP Regen +160%,Vision Range +1.5,"],
["accessory", "emerald_tablet.png", "Emerald Tablet", "Force Core,Flower of Fate", "Legendary", "Attack Power +18,Defense +18,Critical Strike Chance +15%,Cooldown Reduction +10%,"],
["search", "nail.png", "Nail", "Avenue,Archery Range,Factory", 1, 0],
["search", "leather.png", "Leather", "NA", 1, 0],
["search", "turtle_shell.png", "Turtle Shell", "Dock,Pond,Beach", 1, 0],
["search", "rubber.png", "Rubber", "Dock,Alley,Archery Range", 1, 0],
["search", "scrap_metal.png", "Scrap Metal", "Dock,Hotel,Hospital,Factory", 1, 0],
["search", "lighter.png", "Lighter", "Dock,Alley,Factory,School", 1, 0],
["search", "laser_pointer.png", "Laser Pointer", "Uptown,Hospital,School", 1, 0],
["search", "stallion_medal.png", "Stallion Medal", "Beach,Alley,Temple", 1, 0],
["search", "battery.png", "Battery", "Dock,Avenue,Factory", 1, 0],
["search", "alcohol.png", "Alcohol", "Hospital,Factory,School", 1, 0],
["search", "oil.png", "Oil", "Uptown,Avenue,Archery Range,Factory", 1, 0],
["search", "cloth.png", "Cloth", "Hotel,Avenue,Temple", 1, 0],
["search", "gemstone.png", "Gemstone", "Pond,Beach,Temple,Forest", 1, 0],
["search", "glue.png", "Glue", "Alley,Hospital,Factory", 1, 0],
["search", "paper.png", "Paper", "Temple,Archery Range,Chapel", 1, 0],
["search", "iron_ore.png", "Iron Ore", "Hotel,Cemetery,Forest", 1, 0],
["search", "can.png", "Can", "Beach,Avenue,School", 1, 0],
["search", "gunpowder.png", "Gunpowder", "Temple,Archery Range,Cemetery", 1, 0],
["search", "stone.png", "Stone", "NA", 1, 0],
["search", "glass_bottle.png", "Glass Bottle", "Dock,Avenue,Chapel", 1, 0],
["combine", "steel.png", "Steel", "Scrap Metal,Iron Ore", "Uncommon", 2],
["combine", "oilcloth.png", "Oilcloth", "Oil,Bandage", "Uncommon", 2],
["combine", "heated_oil.png", "Heated Oil", "Oil,Lighter", "Uncommon", 3],
["combine", "ruby.png", "Ruby", "Hammer,Gemstone", "Uncommon", 1],
["combine", "dead_battery.png", "Dead Battery", "Battery,Water", "Uncommon", 2],
["combine", "white_powder.png", "White Powder", "Chalk,Stone", "Uncommon", 1],
["search", "tree_of_life.png", "Tree of Life", "NA", 1, 0],
["search", "meteorite.png", "Meteorite", "NA", 1, 0],
["combine", "ash.png", "Ash", "Paper,Lighter", "Uncommon", 1],
["combine", "electronic_parts.png", "Electronic Parts", "Battery,Piano Wire", "Uncommon", 1],
["combine", "blueprint.png", "Blueprint", "Fountain Pen,Paper", "Uncommon", 1],
["combine", "iron_sheet.png", "Iron Sheet", "Scrap Metal,Hammer", "Uncommon", 2],
["combine", "gold.png", "Gold", "Pickaxe,Gemstone", "Uncommon", 1],
["combine", "heated_stone.png", "Heated Stone", "Stone,Lighter", "Uncommon", 3],
["combine", "moonstone.png", "Moonstone", "Meteorite,Stone", "Rare", 1],
["combine", "poison.png", "Poison", "Ash,Water", "Rare", 1],
["combine", "motor.png", "Motor", "Electronic Parts,Scrap Metal", "Rare", 1],
["search", "mithril.png", "Mithril", "NA", 1, 0],
["combine", "glass_panel.png", "Glass Panel", "Glass Pieces,Glue", "Rare", 1],
["combine", "ion_battery.png", "Ion Battery", "Dead Battery,Carbonated Water", "Rare", 2],
["search", "vf_blood_sample.png", "VF Blood Sample", "NA", 1, 0],
["combine", "force_core.png", "Force Core", "Powder of Life,Meteorite", "Epic", 1],
["combine", "cell_phone.png", "Cell Phone", "Blueprint,Electronic Parts", "Rare", 1],
["search", "honey.png", "Honey", "Alley,Avenue,Forest", 1, 0],
["search", "water.png", "Water", "NA", 1, 0],
["search", "ice.png", "Ice", "Hotel,Hospital,Cemetery", 1, 0],
["search", "whiskey.png", "Whiskey", "Uptown,Hotel,Chapel", 1, 0],
["search", "coffee.png", "Coffee", "Dock,Uptown,Cemetery", 1, 0],
["search", "carbonated_water.png", "Carbonated Water", "Beach,Uptown,Hotel", 1, 0],
["search", "milk.png", "Milk", "Avenue,Hospital,Chapel", 1, 0],
["combine", "boiling_water.png", "Boiling Water", "Water,Lighter", "Uncommon", 3],
["combine", "lemonade.png", "Lemonade", "Carbonated Water,Lemon", "Uncommon", 4],
["combine", "water_bottle.png", "Water Bottle", "Water,Glass Bottle", "Uncommon", 2],
["combine", "baijiu.png", "Baijiu", "Alcohol,Lighter", "Uncommon", 1],
["combine", "soju.png", "Soju", "Alcohol,Water", "Uncommon", 2],
["combine", "ice_coffee.png", "Ice Coffee", "Ice,Coffee", "Uncommon", 2],
["combine", "cocktail.png", "Cocktail", "Whiskey,Lemon", "Uncommon", 4],
["combine", "coffee_liqueur.png", "Coffee Liqueur", "Coffee,Alcohol", "Uncommon", 2],
["combine", "cola.png", "Cola", "Carbonated Water,Honey", "Uncommon", 3],
["combine", "latte.png", "Latte", "Milk,Coffee", "Uncommon", 2],
["combine", "honey_milk.png", "Honey Milk", "Milk,Honey", "Uncommon", 2],
["combine", "highball.png", "Highball", "Whiskey,Carbonated Water", "Uncommon", 2],
["combine", "chocolate_milk.png", "Chocolate Milk", "Chocolate,Milk", "Uncommon", 3],
["combine", "honey_water.png", "Honey Water", "Honey,Water", "Uncommon", 2],
["combine", "ice_water.png", "Ice Water", "Ice,Water", "Uncommon", 2],
["combine", "on_the_rocks.png", "On The Rocks", "Ice,Whiskey", "Uncommon", 2],
["combine", "cowboy.png", "Cowboy", "Milk,Whiskey", "Uncommon", 2],
["combine", "kaoliang_liquor.png", "Kaoliang Liquor", "Baijiu,Lighter", "Rare", 3],
["combine", "hot_honey_water.png", "Hot Honey Water", "Boiling Water,Honey", "Rare", 2],
["combine", "flower_liquor.png", "Flower Liquor", "Baijiu,Flower", "Rare", 5],
["combine", "americano.png", "Americano", "Boiling Water,Coffee", "Rare", 2],
["combine", "herbal_liquor.png", "Herbal Liquor", "Baijiu,Oriental Herb", "Rare", 5],
["combine", "whiskey_cocktail.png", "Whiskey Cocktail", "Cola,Whiskey", "Rare", 5],
["combine", "purified_water.png", "Purified Water", "Boiling Water,Ice", "Rare", 2],
["combine", "can_of_cola.png", "Can of Cola", "Cola,Can", "Rare", 2],
["combine", "hot_chocolate.png", "Hot Chocolate", "Boiling Water,Chocolate", "Rare", 4],
["combine", "white_russian.png", "White Russian", "Coffee Liqueur,Milk", "Rare", 4],
["search", "potato.png", "Potato", "NA", 1, 0],
["search", "cod.png", "Cod", "NA", 1, 0],
["search", "lemon.png", "Lemon", "Uptown,Hotel,Hospital", 1, 0],
["search", "garlic.png", "Garlic", "Alley,Temple,Cemetery", 1, 0],
["search", "adhesive_bandage.png", "Adhesive Bandage", "Hospital", 1, 0],
["search", "carp.png", "Carp", "NA", 1, 0],
["search", "bread.png", "Bread", "Dock,Chapel,School", 1, 0],
["search", "meat.png", "Meat", "NA", 1, 0],
["search", "egg.png", "Egg", "Archery Range,Cemetery,Forest", 1, 0],
["search", "ramen.png", "Ramen", "Dock,Alley,Temple", 1, 0],
["search", "oriental_herb.png", "Oriental Herb", "Pond,Temple,Forest", 1, 0],
["search", "chocolate.png", "Chocolate", "Uptown,Avenue,Archery Range", 1, 0],
["search", "curry_powder.png", "Curry Powder", "Uptown,Factory", 1, 0],
["combine", "honey_cod_steak.png", "Honey Cod Steak", "Cod,Honey", "Uncommon", 1],
["combine", "canned_cod_liver.png", "Canned Cod Liver", "Cod,Can", "Uncommon", 1],
["combine", "garlic_bread.png", "Garlic Bread", "Bread,Garlic", "Uncommon", 2],
["combine", "butter.png", "Butter", "Milk,Branch", "Uncommon", 1],
["combine", "herbal_medicine.png", "Herbal Medicine", "Oriental Herb,Turtle Shell", "Uncommon", 1],
["combine", "carp_bread.png", "Carp Bread", "Bread,Carp", "Uncommon", 2],
["search", "holy_water.png", "Holy Water", "NA", 1, 0],
["combine", "disinfectant.png", "Disinfectant", "Alcohol,Adhesive Bandage", "Uncommon", 1],
["combine", "choco_pie.png", "Choco Pie", "Bread,Chocolate", "Uncommon", 1],
["combine", "acupuncture_needle.png", "Acupuncture Needle", "Alcohol,Needle", "Uncommon", 1],
["combine", "orchid.png", "Orchid", "Oriental Herb,Flower", "Uncommon", 2],
["combine", "tandoori_chicken.png", "Tandoori Chicken", "Curry Powder,Meat", "Uncommon", 1],
["combine", "bacon_and_garlic_sticks.png", "Bacon and Garlic Sticks", "Garlic,Meat", "Uncommon", 1],
["combine", "bun.png", "Bun", "Bread,Coffee", "Uncommon", 1],
["combine", "hamburger.png", "Hamburger", "Meat,Bread", "Uncommon", 1],
["combine", "potato_bread.png", "Potato Bread", "Potato,Bread", "Uncommon", 2],
["combine", "potato_soup.png", "Potato Soup", "Potato,Milk", "Uncommon", 1],
["combine", "fish_fillet_with_egg.png", "Fish Fillet With Egg", "Carp,Egg", "Uncommon", 1],
["combine", "citrus_cake.png", "Citrus Cake", "Lemon,Bread", "Uncommon", 2],
["combine", "lemon_ice_cream.png", "Lemon Ice Cream", "Lemon,Egg", "Uncommon", 3],
["combine", "honey_garlic_pickle.png", "Honey Garlic Pickle", "Garlic,Honey", "Uncommon", 3],
["combine", "egg_bun.png", "Egg Bun", "Egg,Bread", "Uncommon", 2],
["combine", "easter_egg.png", "Easter Egg", "Egg,Chocolate", "Uncommon", 1],
["combine", "whisky_bonbon.png", "Whisky Bonbon", "Whiskey,Chocolate", "Uncommon", 3],
["combine", "choco_ice_cream.png", "Choco Ice Cream", "Ice,Chocolate", "Uncommon", 2],
["combine", "curry_bun.png", "Curry Bun", "Curry Powder,Bread", "Uncommon", 2],
["combine", "spicy_fish_stew.png", "Spicy Fish Stew", "Cod,Boiling Water", "Rare", 2],
["combine", "french_fries.png", "French Fries", "Potato,Heated Oil", "Rare", 1],
["combine", "baked_potato.png", "Baked Potato", "Potato,Heated Stone", "Rare", 2],
["combine", "baked_carp.png", "Baked Carp", "Carp,Heated Stone", "Rare", 2],
["combine", "grilled_chilean_sea_bass.png", "Grilled Chilean Sea Bass", "Cod,Heated Stone", "Rare", 3],
["combine", "hot_ramen.png", "Hot Ramen", "Ramen,Boiling Water", "Rare", 2],
["combine", "mocha_bread.png", "Mocha Bread", "Bread,Coffee Liqueur", "Rare", 2],
["combine", "scrambled_egg.png", "Scrambled Egg", "Egg,Heated Oil", "Rare", 2],
["combine", "chocolate_chip_cookies.png", "Chocolate Chip Cookies", "Chocolate,Butter", "Rare", 2],
["combine", "choco_pie_box.png", "Choco Pie Box", "Choco Pie,Box", "Rare", 2],
["combine", "curry.png", "Curry", "Curry Powder,Boiling Water", "Rare", 3],
["combine", "oriental_concoction.png", "Oriental Concoction", "Oriental Herb,Boiling Water", "Rare", 2],
["combine", "honey_butter.png", "Honey Butter", "Butter,Honey", "Rare", 2],
["combine", "fried_chicken.png", "Fried Chicken", "Meat,Heated Oil", "Rare", 2],
["combine", "healing_potion.png", "Healing Potion", "Orchid,Glass Bottle", "Rare", 2],
["combine", "boiled_egg.png", "Boiled Egg", "Egg,Boiling Water", "Rare", 2],
["combine", "pound_cake.png", "Pound Cake", "Butter,Bread", "Rare", 2],
["combine", "curry_croquette.png", "Curry Croquette", "Curry Powder,Heated Oil", "Rare", 2],
["combine", "steak.png", "Steak", "Meat,Heated Stone", "Rare", 4],
["combine", "first_aid_kit.png", "First Aid Kit", "Disinfectant,Bandage", "Rare", 1],
["combine", "butter-fried_potatoes.png", "Butter-Fried Potatoes", "Potato,Butter", "Rare", 2],
["combine", "fish_cutlet.png", "Fish Cutlet", "Cod,Heated Oil", "Rare", 1],
["combine", "stir_fried_ramen.png", "Stir Fried Ramen", "Ramen,Heated Oil", "Rare", 2],
["combine", "cold_noodles.png", "Cold Noodles", "Ramen,Ice Water", "Rare", 2],
["combine", "zen_vitality.png", "Zen Vitality", "Acupuncture Needle,Herbal Medicine", "Rare", 2],
["combine", "fish_and_chips.png", "Fish And Chips", "Fish Cutlet,French Fries", "Epic", 2],
["combine", "garlic_ramen.png", "Garlic Ramen", "Hot Ramen,Garlic", "Rare", 2],
["search", "surveillance_camera.png", "Surveillance Camera", "Dock,Beach,Uptown,Avenue,Hospital,Archery Range,Cemetery,School", 1, 0],
["search", "snare.png", "Snare", "Dock,Pond,Beach,Archery Range,Forest,Chapel", 1, 0],
["search", "mousetrap.png", "Mousetrap", "Pond,Beach,Cemetery", 1, 0],
["search", "piano_wire.png", "Piano Wire", "Beach,Uptown,Hotel,Chapel", 1, 0],
["combine", "spiked_plank.png", "Spiked Plank", "Mousetrap,Nail", "Uncommon", 2],
["combine", "enhanced_mousetrap.png", "Enhanced Mousetrap", "Mousetrap,Iron Ore", "Uncommon", 2],
["combine", "dynamite.png", "Dynamite", "Piano Wire,Gunpowder", "Uncommon", 1],
["combine", "bamboo_trap.png", "Bamboo Trap", "Snare,Bamboo", "Uncommon", 2],
["combine", "booby_trap.png", "Booby Trap", "Snare,Glue", "Uncommon", 2],
["combine", "clang_clatter.png", "Clang Clatter", "Can,Iron Ball", "Uncommon", 3],
["combine", "telephoto_camera.png", "Telephoto Camera", "Surveillance Camera,Binoculars", "Uncommon", 3],
["combine", "jungle_guillotine.png", "Jungle Guillotine", "Mousetrap,Rusty Sword", "Uncommon", 1],
["combine", "mine.png", "Mine", "Booby Trap,Gunpowder", "Rare", 2],
["combine", "pendulum_axe.png", "Pendulum Axe", "Bamboo Trap,Hatchet", "Rare", 2],
["combine", "explosive_trap.png", "Explosive Trap", "Mousetrap,Gunpowder", "Uncommon", 1],
["combine", "rdx.png", "RDX", "Dynamite,Scrap Metal", "Rare", 1],
["combine", "mithril_string.png", "Mithril String", "Mithril,Piano Wire", "Rare", 3],
["combine", "stingburst.png", "Stingburst", "RDX,Spiked Plank", "Epic", 1],
["combine", "fire_trap.png", "Fire Trap", "Explosive Trap,Oilcloth", "Rare", 3],
["combine", "c-4.png", "C-4", "RDX,White Powder", "Epic", 3],
["combine", "double_guillotine.png", "Double Guillotine", "Jungle Guillotine,Pendulum Axe", "Epic", 2],
["combine", "claymore.png", "Claymore", "Mine,Explosive Trap", "Epic", 2],
["combine", "hidden_maiden.png", "Hidden Maiden", "Spiked Plank,Jungle Guillotine", "Rare", 2],
["combine", "remote_mine.png", "Remote Mine", "Force Core,Spiked Plank", "Legendary", 3],
["combine", "smart_bomb.png", "Smart Bomb", "RDX,Cell Phone", "Legendary", 3]];
